"""Produce real SHAP explanations from the trained ensemble (Build-Instructions T3.1 VERIFY).

T3.1's VERIFY condition is: *"Given a sample flagged detection, output includes a ranked feature
list a reader can map back to the original feature names (not just indices)."* This script
demonstrates that on the ACTUAL trained model from T2.6, not on synthetic data, and writes the
output to `reports/t3_1_shap_examples.md` so a teammate can read it without running anything.

`reports/t3_1_shap_examples.md` is also the artefact T3.3's comprehensibility check uses: a team
member unfamiliar with the model internals should be able to read one of these and state, in their
own words, why the flow was flagged (`TRD.md §9`, "XAI output is usable").

Prerequisite: run `notebooks/03_train_ensemble_iotid20.ipynb`, which writes `artifacts/`.

Usage:
    .venv/bin/python scripts/demo_shap_explanation.py
"""

from __future__ import annotations

import json
import logging
import sys
import warnings
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import numpy as np  # noqa: E402
from tensorflow import keras  # noqa: E402
from src.models.train_utils import load_branch  # noqa: E402

from src.config import ARTIFACTS_DIR, POSITIVE_CLASS_NAME, POSITIVE_LABEL, REPORTS_DIR  # noqa: E402
from src.evaluation.metrics import POSITIVE_CLASS_STATEMENT  # noqa: E402
from src.xai.shap_explainer import EnsembleShapExplainer  # noqa: E402

warnings.filterwarnings("ignore")
logging.basicConfig(level=logging.WARNING, format="%(levelname)s | %(message)s")

#: How many flagged detections to explain in the report.
N_EXAMPLES: int = 3
#: Background windows drawn from the TRAINING fold (never from test -- that would leak).
BACKGROUND_SIZE: int = 100


def main() -> None:
    """Load the trained ensemble, explain a few flagged detections, and write the report."""
    if not (ARTIFACTS_DIR / "ensemble_artifacts.npz").exists():
        raise SystemExit(
            "artifacts/ not found. Run notebooks/03_train_ensemble_iotid20.ipynb first."
        )

    data = np.load(ARTIFACTS_DIR / "ensemble_artifacts.npz")
    meta = json.loads((ARTIFACTS_DIR / "feature_names.json").read_text(encoding="utf-8"))
    feature_names = meta["feature_names"]
    branch_names = meta["branch_names"]

    models = {
        name: load_branch(ARTIFACTS_DIR / "models" / f"{name}.keras")
        for name in branch_names
    }
    print(f"Loaded {len(models)} branches; {len(feature_names)} features; "
          f"{data['X_test'].shape[0]:,} test windows")

    explainer = EnsembleShapExplainer(
        models,
        feature_names,
        data["X_background"],
        background_size=BACKGROUND_SIZE,
    )

    X_test = data["X_test"]
    y_test = data["y_test"]
    predictions = data["fused_predictions"]

    # Explain TRUE positives -- flows the model flagged as Attack that really are attacks.
    correct_flags = np.flatnonzero((predictions == POSITIVE_LABEL) & (y_test == POSITIVE_LABEL))
    # ...and one false alarm, which is what an operator most needs an explanation for.
    false_alarms = np.flatnonzero((predictions == POSITIVE_LABEL) & (y_test != POSITIVE_LABEL))

    chosen: list[tuple[str, int]] = [
        (f"True positive #{i + 1}", int(index))
        for i, index in enumerate(correct_flags[:N_EXAMPLES])
    ]
    if len(false_alarms):
        chosen.append(("False alarm (a Normal window flagged as Attack)", int(false_alarms[0])))

    lines = [
        "# T3.1 — SHAP explanations from the trained ensemble",
        "",
        "**Task:** T3.1 · **Generated by:** `scripts/demo_shap_explanation.py` · "
        "**Model:** the trained ensemble from T2.6 (`artifacts/`)",
        "",
        f"> {POSITIVE_CLASS_STATEMENT}",
        "",
        "These are real explanations of real detections on the held-out test fold, produced by the",
        "same confidence-weighted ensemble evaluated in `reports/phase2_results.md`. Method and",
        "rationale: `docs/xai_survey.md` (SHAP primary, LIME fallback); construction for a",
        "non-differentiable fusion: `src/xai/shap_explainer.py`'s module docstring.",
        "",
        "**How to read one.** Each explanation names the measurements that moved the decision, how",
        "much of the total evidence each accounted for, and where in the 10-record window it",
        "mattered most. Feature names are the original IoTID20 column names, so every line can be",
        "traced back to the traffic itself.",
        "",
        "---",
        "",
    ]

    for title, index in chosen:
        explanation = explainer.explain(X_test[index])
        actual = POSITIVE_CLASS_NAME if y_test[index] == POSITIVE_LABEL else "Normal"

        print(f"\n=== {title} (test window {index}) ===")
        print(explanation.to_summary())

        lines += [
            f"## {title}",
            "",
            f"*Test window {index} · actual class: **{actual}** · "
            f"model said: **{explanation.predicted_class_name()}***",
            "",
            "```",
            explanation.to_summary(),
            "```",
            "",
            "| Rank | Feature | Attribution | Share of evidence | Pushes toward | Peak record |",
            "|---:|---|---:|---:|---|---:|",
        ]
        for row in explanation.as_table():
            lines.append(
                f"| {row['rank']} | `{row['feature']}` | {row['attribution']:+.5f} | "
                f"{row['share_of_total']:.1%} | {row['pushes_toward']} | "
                f"{row['peak_timestep'] + 1} of 10 |"
            )
        lines += ["", "---", ""]

    lines += [
        "## Caveats",
        "",
        "- The fusion layer is not differentiable end to end (its weights depend on each branch's",
        "  own softmax), so SHAP is run **per branch** and the three attribution maps are",
        "  recombined with the same confidence weights the fusion used. That recombination is",
        "  **this project's own construction**, justified by linearity, not off-the-shelf SHAP.",
        "- Attributions are summed across the window's 10 timesteps to give one number per feature.",
        "  Summing preserves SHAP's additivity; the full per-timestep map is kept in",
        "  `Explanation.timestep_attributions`.",
        "- Attribution *quality* is not established by these examples. Fidelity and stability are",
        "  measured in T3.3; this document only demonstrates the output contract.",
        "- Background windows are drawn from the **training** fold. Drawing them from test data",
        "  would leak the evaluation set into the explanations.",
        "",
        "## An open usability question for T3.3",
        "",
        "Features are ranked by **absolute** influence, which is the standard SHAP presentation and",
        "is what makes `share_of_evidence` add to 100%. A side effect is visible above: for several",
        "ATTACK verdicts the top-ranked feature *lowered* the suspicion score. That is truthful —",
        "it was the single most influential measurement, and it argued the other way — but it may",
        "read as contradictory to someone opening an alert.",
        "",
        "This is exactly what T3.3's comprehensibility check should test on a real reader rather",
        "than us deciding by intuition. The alternatives, if it proves confusing, are to rank only",
        "features supporting the verdict (loses the honest counter-evidence), or to split the list",
        "into 'supported the alert' and 'argued against it' (keeps everything, costs brevity). No",
        "change has been made yet, because `docs/xai_survey.md` does not specify one and guessing",
        "would be the undocumented drift this project criticises.",
    ]

    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    output = REPORTS_DIR / "t3_1_shap_examples.md"
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\nWrote {output}")


if __name__ == "__main__":
    main()
