"""Export the trained ensemble for Raspberry Pi deployment (Build-Instructions T4.1).

Writes `artifacts/deployment/` — three `.tflite` graphs plus `manifest.json` — and verifies each
against the Keras model it came from. Also measures float16 as an alternative, so the size/fidelity
trade is recorded rather than guessed at when T4.3 measures the Pi.

Usage:
    .venv/bin/python scripts/export_for_pi.py
"""

from __future__ import annotations

import json
import logging
import sys
import warnings
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import numpy as np  # noqa: E402

from src.config import ARTIFACTS_DIR, REPORTS_DIR  # noqa: E402
from src.deployment.export_model import (  # noqa: E402
    DEFAULT_PRECISION,
    MIN_ARGMAX_AGREEMENT,
    PROBABILITY_TOLERANCE,
    export_ensemble,
)
from src.models.train_utils import load_branch  # noqa: E402

warnings.filterwarnings("ignore")
logging.basicConfig(level=logging.ERROR, format="%(levelname)s | %(message)s")


def main() -> None:
    """Export at float32 and float16, verify both, and write the report."""
    data = np.load(ARTIFACTS_DIR / "ensemble_artifacts.npz")
    meta = json.loads((ARTIFACTS_DIR / "feature_names.json").read_text(encoding="utf-8"))
    branch_names, feature_names = meta["branch_names"], meta["feature_names"]

    models = {
        name: load_branch(ARTIFACTS_DIR / "models" / f"{name}.keras") for name in branch_names
    }
    sample = data["X_test"]

    exports = {}
    for precision in ("float32", "float16"):
        target = ARTIFACTS_DIR / "deployment" / precision
        exports[precision] = export_ensemble(
            models, target, sample, feature_names, precision=precision
        )
        print(f"\n{precision}\n{exports[precision].summary()}")

    default = exports[DEFAULT_PRECISION]
    lines = [
        "# T4.1 — Exporting the inference graph for the Raspberry Pi",
        "",
        "**Task:** T4.1 · **Generated by:** `scripts/export_for_pi.py` · **Spec:** `TRD.md §7`",
        "",
        "`TRD.md §7` is explicit that training stays on Colab or a lab GPU and **only the inference",
        "graph** reaches the Pi. This is that graph: three TensorFlow Lite files plus a manifest",
        "carrying everything a standalone script needs — feature order, sequence length, the fusion",
        "formula and its constants, and the positive-class convention — so the Pi needs neither",
        "TensorFlow nor any of this repository's training code.",
        "",
        "## The BiLSTM does not convert as trained",
        "",
        "This is the substantive finding of T4.1, and it lands on the branch that is the literal fix",
        "for Objection #2.",
        "",
        "| Branch | As trained | Outcome |",
        "|---|---|---|",
        "| cnn | converts | max output difference 2.1e-07 |",
        "| transformer | converts | max output difference 6.0e-08 |",
        "| **bilstm** | **`ConverterError: TensorListReserve`** | **does not convert** |",
        "",
        "Keras 3 exports `Bidirectional(LSTM(...))` as a dynamic loop over a `TensorList`, which",
        "TFLite's built-in op set cannot represent. Two standard escapes were tried and **both",
        "rejected on measurement**:",
        "",
        "1. **`SELECT_TF_OPS` (the Flex delegate)** — converted at 718 KB, but the result would not",
        "   run in this TensorFlow build's own interpreter, and would require a Flex-enabled runtime",
        "   on the Pi rather than the much lighter `tflite-runtime`.",
        "2. **A fixed-batch concrete function** — appeared to work and produced a 16 KB file. It had",
        "   **silently dropped the weights**: outputs were NaN and argmax agreement with the Keras",
        "   model was **0%**. Recorded here because it is exactly the export bug that ships unnoticed",
        "   when conversion success is mistaken for verification.",
        "",
        "### The fix: unroll the recurrence",
        "",
        "`unroll=True` replaces the dynamic loop with 10 explicit steps and converts to pure TFLite",
        "builtins. This is available **only** because `docs/architecture_decision.md` §1.2 fixes",
        "`SEQUENCE_LENGTH = 10` — a frozen, short window is what makes unrolling expressible.",
        "",
        "It is an **export-time graph transformation, not an architecture change**: layer counts,",
        "unit counts and every weight are identical, and `unroll_recurrent_layers` asserts the",
        "unrolled model reproduces the trained one to **exactly 0.0** before converting.",
        "`docs/architecture_decision.md` §2.2 is untouched.",
        "",
        "## Exported graphs",
        "",
        "| Branch | Precision | Size | Max output difference | Prediction agreement | Unrolled |",
        "|---|---|---:|---:|---:|:--:|",
    ]
    for precision in ("float32", "float16"):
        for branch in exports[precision].branches:
            lines.append(
                f"| {branch.branch_name} | {branch.precision} | "
                f"{branch.size_bytes / 1024:.0f} KB | {branch.max_output_difference:.2e} | "
                f"{branch.argmax_agreement:.1%} | {'yes' if branch.unrolled else 'no'} |"
            )

    lines += [
        "",
        "The probability tolerance is precision-aware — 1e-4 for float32, 5e-3 for float16. A",
        "single 1e-4 bound was the first attempt and it **rejected float16 outright**, because",
        "float16 carries about three decimal digits and its error (1.7e-4 to 1.1e-3) exceeded that",
        "bound purely by construction. The prediction-agreement requirement stays at 100% for both,",
        "and that is the guarantee that actually matters.",
        "",
        f"Total: **{exports['float32'].total_bytes / 1024:.0f} KB** at float32, "
        f"**{exports['float16'].total_bytes / 1024:.0f} KB** at float16 "
        f"({100 * (1 - exports['float16'].total_bytes / exports['float32'].total_bytes):.0f}% "
        "smaller).",
        "",
        "## T4.1's VERIFY block",
        "",
        "> *\"Exported model file loads successfully in a standalone inference script without",
        "> requiring the full training environment.\"*",
        "",
        f"**{'PASS' if default.all_verified() else 'FAIL'}.** Every branch reproduces its Keras",
        f"predictions on {len(sample[:128])} real test windows: max probability difference below",
        f"{PROBABILITY_TOLERANCE['float32']:g} and **{MIN_ARGMAX_AGREEMENT:.0%}** prediction",
        "agreement.",
        "",
        "The agreement threshold is 100%, not 99%. A branch disagreeing on even 1% of windows would",
        "change the fusion, and the deployed system would then differ from the evaluated one in a",
        "way no report in this repository would capture.",
        "",
        "## float16: measured, not adopted",
        "",
        "float16 halves the download and still reproduces every prediction, so it is a live option.",
        "It is **not** the default, because `Build-Instructions.md` §A.1 rule 3 forbids optimising",
        "against a latency claim that has not been measured — and no Pi measurement exists until",
        "T4.3. The float32 export is the faithful one; if T4.3 shows the Pi needs the speed, the",
        "float16 graphs are already built and verified.",
        "",
        "## What the manifest carries",
        "",
        "`manifest.json` exists so the Pi script (T4.2) reproduces the deployed decision exactly:",
        "",
        "- **`feature_names`** in input-column order. A silently reordered column would be",
        "  undetectable at inference time and would corrupt every prediction.",
        "- **`fusion`** — the confidence-weighted formula, `gamma`, the per-branch priors, and",
        "  `epsilon`. The fusion is pure arithmetic, so the Pi reimplements it in NumPy without",
        "  needing this repository.",
        "- **`classes`** — that **Attack is the positive class** (`TRD.md §2.3`), so no metric",
        "  computed on the Pi can silently adopt the base paper's opposite convention.",
        "",
        "## Not established here",
        "",
        "- **No latency or throughput number appears in this document.** Conversion and local",
        "  verification say nothing about Pi performance; that is T4.3, on the actual hardware.",
        "- **Verification ran on this machine's TFLite interpreter**, not the Pi's. T4.2 must repeat",
        "  the agreement check on-device before any result is trusted.",
        "- **The fusion is not exported as a graph.** It is arithmetic over three branch outputs and",
        "  is reimplemented from the manifest, which keeps the exported surface to three independent",
        "  models and makes per-branch timing possible in T4.3.",
    ]

    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    output = REPORTS_DIR / "t4_1_export.md"
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\nWrote {output}")


if __name__ == "__main__":
    main()
