"""Final comparative analysis (Build-Instructions T4.4; PRD.md §10).

Writes `reports/final_comparison.md`, summarising this project against (a) its own leakage-free
baseline and (b) the base paper's published numbers.

>>> THE BINDING CONSTRAINT ON THIS FILE <<<
`Build-Instructions.md` §A.1 and T4.4's VERIFY block forbid citing HIDS-IoMT's
99.92 / 99.91 / 99.99 / 99.95 without the metric-inversion caveat **in the same paragraph**.
`BASE_PAPER_CAVEAT` below is the single string used at every such citation, and
`tests/test_report_integrity.py` scans the whole repository to confirm no base-paper number appears
anywhere without it. The rule is enforced mechanically because a rule that depends on remembering
gets forgotten precisely when the numbers are inconvenient.

Numbers are read from the generated CSVs rather than transcribed, so this document cannot drift
from the measurements it summarises.

Usage:
    .venv/bin/python scripts/final_comparison.py
"""

from __future__ import annotations

import logging
import sys
import warnings
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import pandas as pd  # noqa: E402

from src.config import REPORTS_DIR  # noqa: E402
from src.evaluation.metrics import POSITIVE_CLASS_STATEMENT  # noqa: E402

warnings.filterwarnings("ignore")
logging.basicConfig(level=logging.ERROR)

#: The base paper's headline figures. Never write these anywhere without `BASE_PAPER_CAVEAT`.
BASE_PAPER_ACCURACY = "99.92%"
BASE_PAPER_PRECISION = "99.91%"
BASE_PAPER_RECALL = "99.99%"
BASE_PAPER_F1 = "99.95%"

#: The caveat that must accompany every citation of the numbers above (`PRD.md §2.1.3`, `§10`).
BASE_PAPER_CAVEAT = (
    "**These figures carry two defects and must never be quoted without them.** First, the "
    "precision and recall labels are very likely *swapped*: the paper defines its positive class "
    "as *Normal* and labels both Equations 7 and 8 \"Recall\", one of which is the precision "
    "formula. Recomputing from its own Fig. 11c confusion matrix (87,987 / 77 / 9 / 28,996) "
    "reproduces the reported accuracy exactly but shows the reported \"precision\" (99.913%) is "
    "the true recall and the reported \"recall\" (99.99%) is the true precision "
    "(`PRD.md §10`). Second, the evaluation fold was contaminated: the paper's post-SMOTE instance "
    "count of 1,170,684 is reproduced *exactly* by balancing IoTID20's cleaned majority class "
    "(2 x 585,342), so its train/test/validation folds partition synthetic data — reproduced "
    "empirically in `notebooks/01_reproduce_leakage.ipynb`, where 46.61% of the resulting test "
    "fold never existed in the real capture."
)


def main() -> None:
    """Assemble the final comparison from the generated result tables."""
    ablation = pd.read_csv(REPORTS_DIR / "t4_4_ablation.csv")
    baseline = pd.read_csv(REPORTS_DIR / "t1_2_leakage_free_baseline.csv").iloc[0]
    leaky = pd.read_csv(REPORTS_DIR / "t1_1_leaky_result.csv").iloc[0]

    best_single = ablation[ablation.group == "single branch"].sort_values("f1").iloc[-1]
    full = ablation[ablation.model.str.contains("FULL ENSEMBLE")].iloc[0]

    lines = [
        "# Final comparison — what this project established",
        "",
        "**Task:** T4.4 · **Generated by:** `scripts/final_comparison.py`",
        "",
        f"> {POSITIVE_CLASS_STATEMENT}",
        "",
        "Numbers are read from the generated result tables, not transcribed, so this document",
        "cannot drift from the measurements it summarises.",
        "",
        "---",
        "",
        "## 1. The four objections, and what came of each",
        "",
        "| # | Objection to HIDS-IoMT | Status | Evidence |",
        "|---|---|---|---|",
        "| 1 | Pre-split SMOTE inflates the headline number | **Confirmed, and fixed** | "
        "`notebooks/01_reproduce_leakage.ipynb`, `02_leakage_free_baseline.ipynb` |",
        "| 2 | The LSTM is never specified; input is a single record | **Fixed** | "
        "`docs/architecture_decision.md`, `reports/phase2_results.md` §2 |",
        "| 3 | Precision and recall labels are swapped | **Confirmed by re-derivation** | "
        "`PRD.md §10`; every table in this repo states its positive class |",
        "| 4 | Black box, flat 500 ms threshold for every device | **Partly fixed** | "
        "`reports/t3_3_xai_evaluation.md`, `reports/t3_4_adaptive_threshold.md` |",
        "",
        "### Objection 1 — confirmed more strongly than the PRD claimed",
        "",
        "IoTID20's cleaned majority class is 585,342 rows, and 2 x 585,342 = **1,170,684**, which",
        "reproduces the base paper's stated post-SMOTE total **exactly**. Its train/test/validation",
        "totals therefore partition synthetic data. Reproducing that pipeline order put **46.61%**",
        "of the test fold into rows that never existed in the real capture, and 93.21% of its",
        "minority-class rows.",
        "",
        "One correction in the other direction, recorded because this project does not get to round",
        "in its own favour: `PRD.md §2.1.1` says the paper's split totals match its post-SMOTE count",
        "\"exactly\". They sum to 1,170,686 — **two more**. Trivial, and it does not weaken the",
        "objection, but the PRD's wording should read \"within 2 rows of\".",
        "",
        "### An additional defect this project found",
        "",
        "**58.2% of cleaned IoTID20 rows are exact duplicates.** Random splitting puts identical",
        "records on both sides regardless of when SMOTE runs, and neither the base paper nor the",
        "senior's prior work mentions deduplication. Fixing the SMOTE ordering alone did **not**",
        "lower the accuracy; the duplicates were the larger leakage vector.",
        "",
        "## 2. This project's own numbers",
        "",
        "### 2.1 Establishing an honest baseline",
        "",
        "| Pipeline | Accuracy | Precision | Recall | F1 | Test fold synthetic | Near-duplicate |",
        "|---|---:|---:|---:|---:|---:|---:|",
        f"| A. Leaky (base paper's order) | {leaky['accuracy']:.4f} | {leaky['precision']:.4f} | "
        f"{leaky['recall']:.4f} | {leaky['f1']:.4f} | 46.61% | 43.98% |",
        f"| **C. Leakage-free + deduplicated** | **{baseline['accuracy']:.4f}** | "
        f"**{baseline['precision']:.4f}** | **{baseline['recall']:.4f}** | "
        f"**{baseline['f1']:.4f}** | **0.00%** | **5.70%** |",
        "",
        "Pipeline C is this project's baseline. It is a Random Forest on individual flow records.",
        "",
        "### 2.2 The ensemble",
        "",
        "| Model | Accuracy | Precision | Recall | F1 |",
        "|---|---:|---:|---:|---:|",
        f"| **{best_single['model']}** | {best_single['accuracy']:.4f} | "
        f"{best_single['precision']:.4f} | {best_single['recall']:.4f} | "
        f"**{best_single['f1']:.4f}** |",
        f"| Full three-branch ensemble | {full['accuracy']:.4f} | {full['precision']:.4f} | "
        f"{full['recall']:.4f} | {full['f1']:.4f} |",
        "",
        f"**The best single branch beats the ensemble** ({best_single['f1']:.4f} vs "
        f"{full['f1']:.4f}). Both candidate fixes — per-branch calibration and fitted fusion priors",
        "— were measured and both failed (`docs/calibration_decision.md`). The branches agree on",
        "90.9% of windows, so any fusion rule has a ceiling of +0.026 accuracy over the best branch.",
        "",
        "**These numbers are not comparable to §2.1's.** The baseline classifies flow *records*;",
        "the ensemble classifies 10-record *windows*, on session-level folds, with class weights",
        "rather than SMOTE. Three variables differ, so the difference is not attributable to",
        "architecture (`reports/phase2_results.md` §5).",
        "",
        "## 3. Against the base paper",
        "",
        f"HIDS-IoMT reports {BASE_PAPER_ACCURACY} accuracy, {BASE_PAPER_PRECISION} precision, "
        f"{BASE_PAPER_RECALL} recall, and {BASE_PAPER_F1} F1 on IoTID20. {BASE_PAPER_CAVEAT}",
        "",
        "**No comparison of this project's numbers against those is offered, because none would be",
        "meaningful.** A number produced on a contaminated evaluation fold and a number produced on",
        "a clean one do not measure the same thing, and placing them in a table side by side would",
        "imply otherwise. `PRD.md §5.3` puts beating that figure explicitly out of scope, and",
        "`PRD.md §3` defines success as fixing the four defects rather than exceeding a disputed",
        "value.",
        "",
        "What can be said: this project's leakage-free baseline reaches "
        f"**{baseline['f1']:.4f} F1** on a test fold that is 0.00% synthetic, with the positive",
        "class stated and every metric hand-verified against its confusion matrix.",
        "",
        "## 4. Against the senior's prior work",
        "",
        "`PRD.md §2.2` lists five gaps in the Badiyani stacking ensemble. Four are addressed:",
        "",
        "| Gap | Addressed? |",
        "|---|---|",
        "| Wrong domain (CICIDS2017, no IoMT traffic) | Yes — IoTID20 throughout |",
        "| No temporal modelling | Yes — 10-record sequences, BiLSTM and attention branches |",
        "| No deployment evidence despite a real-time claim | **Partly** — the export is built and verified, but no Pi measurement exists (§6) |",
        "| IQR outlier removal deletes rare attacks | Yes — no outlier removal in this pipeline |",
        "| No repeated runs or significance testing | **No** — this project inherits the same gap (§5) |",
        "",
        "## 5. What this project did not establish",
        "",
        "Listed because a comparison that reports only its wins is the failure mode this whole",
        "project was built to criticise.",
        "",
        "1. **The ensemble does not beat its best single branch on IoTID20.** Reported in full in",
        "   `reports/ablation_study.md`, including that removing the CNN *improves* the ensemble.",
        "2. **`PRD.md §3`'s >30% false-positive reduction target was not met.** The best measured",
        "   reduction is −10.8%, and the criticality labels driving it are synthetic because IoTID20",
        "   contains no medical devices (`reports/t3_4_adaptive_threshold.md`).",
        "3. **No Raspberry Pi latency or throughput number exists.** The hardware is not available;",
        "   the code refuses to emit one off-device (§6).",
        "4. **Edge-IIoTset (T3.6) was not run**, so every conclusion here is IoTID20-only.",
        "5. **Single seed, single split, no significance testing** — the same omission this project",
        "   criticises in the prior work.",
        "6. **T3.3's human readability gate is open.** The quantitative XAI metrics pass, but the",
        "   reader test in `reports/t3_3_reader_test.md` needs a person to complete it.",
        "7. **LIME proved unusable** as an operator-facing explainer: 0.27 top-5 Jaccard under 1%",
        "   input noise, and no statistically significant fidelity at any k",
        "   (`reports/t3_3_xai_evaluation.md`).",
        "",
        "## 6. Deployment status",
        "",
        "The inference graph is exported, verified, and bundled: three TFLite models totalling",
        "1.4 MB (798 KB at float16), reproducing the evaluated ensemble's predictions with **100%**",
        "agreement, plus a standalone runner that imports nothing from this repository",
        "(`reports/t4_1_export.md`, `docs/raspberry_pi_setup.md`).",
        "",
        "**No latency or throughput figure appears anywhere in this repository**, because the",
        "Raspberry Pi 4B has not been connected. `src/deployment/benchmark.py` raises",
        "`NotOnTargetHardwareError` rather than writing a report off-device. `PRD.md §2.2`'s",
        "objection to the prior work is a real-time claim with no hardware behind it, and the",
        "prohibition is enforced in code rather than left to discipline.",
        "",
        "## 6b. Network-level validation (NS-3 — simulated, never measured)",
        "",
        "`NS3-Simulation.md` folds a network simulation into Phase 4. It answers a question the",
        "record- and window-level results cannot: how the *threshold rule* behaves at network scale,",
        "with 20 legitimate wearables, 60 attacker-bots and 4 fog nodes. Full results in",
        "`reports/ns3_simulation_results.md`; every number there is NS-3 output.",
        "",
        "| Rule | False-positive alerts | Wearables blocked | Attackers blocked |",
        "|---|---:|---:|---:|",
        "| fixed (the base paper's flat 500 ms) | 60 | **20/20** | 60/60 |",
        "| ewma (congestion-adaptive) | 36 | 8/20 | 60/60 |",
        "| **criticality (this project, T3.4)** | **29** | 9/20 | 60/60 |",
        "",
        "**The base paper's flat threshold blocks every legitimate wearable in the simulation.**",
        "That is Objection #4's second half with a number attached, and it is the clearest single",
        "piece of evidence this project has for the criticality weighting being worth its complexity.",
        "",
        "Two things this does NOT do, both of which matter more than the table:",
        "",
        "1. **It does not meet `PRD.md §3.1`'s >30% false-positive-reduction target.** The -51.7%",
        "   above is a different quantity that shares a name: legitimate devices quarantined by a",
        "   *timing rule* in a simulation, not the *ensemble's* false-positive rate on unseen attack",
        "   types. The latter is §5's -10.8%, and it remains unmet.",
        "2. **It does not supply a deployment latency.** NS-3's delays are simulated network transit;",
        "   the IDS inspection cost is modelled inside the fog application, where FlowMonitor cannot",
        "   see it. Every latency fed to the simulation is a swept value, because no Pi measurement",
        "   exists and the base paper publishes none (`docs/latency_provenance.md`).",
        "",
        "The simulation did produce one finding of its own: a detection threshold multiplied by a",
        "queue-load term collapses to zero at one end of that term's range, so a congestion-adaptive",
        "rule stops alerting entirely -- under load, it recorded 8 alerts and 0 of 60 attackers",
        "blocked. This project's criticality rule is immune only because its load term is bounded and",
        "clamped (`docs/zero_detection_investigation.md`).",
        "",
        "## 7. What this project actually contributes",
        "",
        "1. **A reproducible demonstration that HIDS-IoMT's evaluation fold was contaminated**, with",
        "   the arithmetic matching its own published totals exactly.",
        "2. **A re-derivation showing its precision and recall labels are swapped**, from its own",
        "   confusion matrix.",
        "3. **A previously unreported defect in IoTID20's use across this literature**: 58.2%",
        "   duplicate rows, a larger leakage vector than the SMOTE ordering.",
        "4. **A fully specified sequence architecture** — every layer, unit, head and window count",
        "   documented in code and asserted by test. The direct fix for Objection #2.",
        "5. **Measured evidence that IoTID20's IP-pair graph cannot support a GNN** (99.68% of nodes",
        "   have degree ≤ 1) — worth stating for anyone proposing graph-based IDS on flow records.",
        "6. **An explainability layer that certifies each explanation before showing it**, and",
        "   labels the 18% it cannot vouch for rather than hiding them.",
        "7. **A set of negative results**: the ensemble does not beat its best branch, calibration",
        "   does not help, fitted fusion priors overfit, and LIME is too unstable to show an",
        "   operator. Each is measured, reproducible, and reported.",
    ]

    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    output = REPORTS_DIR / "final_comparison.md"
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {output}")


if __name__ == "__main__":
    main()
